#!/usr/bin/env python3
"""Print a stub entity for one exercise module, so its testbench can be type-checked.

An exercise ships a testbench but not the module, so without an entity the build can only
parse it: a wrong port order, width or type in a file we hand out would reach a student as
an error they cannot tell apart from their own.

`diagrams/exercises.py` already declares every exercise entity, because the module figures
are drawn from it. Emitting that declaration as VHDL turns three artifacts that used to
agree only by hand, the figure, the exercise text and the testbench, into one checked chain.

The architecture is deliberately empty. Nothing here is a solution, and nothing here is ever
elaborated: `ci/build.sh` analyzes only. Once a solution is published, `ci/extract_vhdl.py`
supplies the real body and the testbench can be run for real.

    ci/entity_stub.py counter > counter_stub.vhd
"""

from __future__ import annotations

import sys
from pathlib import Path

# The entities live next to the drawing code, so `diagrams` has to be importable. Only
# `entity` and `exercises` are imported, and neither needs matplotlib or schemdraw.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "diagrams"))

import exercises  # noqa: E402
from entity import Entity  # noqa: E402


def stub(entity: Entity) -> str:
    """Render one entity as compilable VHDL, with an empty architecture."""
    # Say in the file itself that it is generated and is not a solution, since it lands in a
    # work library beside the student's own code.
    lines = [
        "-- Generated by ci/entity_stub.py from diagrams/exercises.py. Not a solution:",
        "-- the architecture is empty, and this file is analyzed but never elaborated.",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        f"entity {entity.name} is"]

    # Generics first, as VHDL requires, and only when the entity has any. Defaults are
    # included, so a testbench that leaves a generic out of its `generic map` is checked
    # against the value the exercise promises rather than failing to analyze at all.
    if entity.generics:
        lines.append(f"    generic({'; '.join(entity.generic_decls)});")

    # Inputs then outputs, in declaration order, because the testbenches map by position.
    ports = [(p, "in") for p in entity.inputs] + [(p, "out") for p in entity.outputs]

    # Pad the names to the longest so the declarations line up, as they do in a hand-written
    # entity. The continuation indent matches the width of "    port(".
    width = max(len(p.name) for p, _ in ports)
    body = [f"{p.name.ljust(width)}: {d:<3} {p.vhdl_type}" for p, d in ports]
    lines.append("    port(" + (";\n         ".join(body)) + ");")

    # The empty architecture. Analyzing needs it to exist; nothing ever elaborates it.
    lines += [
        "end entity;",
        "",
        f"architecture stub of {entity.name} is",
        "begin",
        "end architecture;",
        ""]
    return "\n".join(lines)


def main() -> int:
    """Print the stub entity for the exercise module named in argv.

    Exit code 0 on success, 1 if no exercise declares that module, 2 on bad usage.
    """
    # Exactly one argument, the module name. The summary line of this file is the usage text.
    if len(sys.argv) != 2:
        print(__doc__.strip().splitlines()[0], file=sys.stderr)
        return 2

    # `BY_LECTURE` groups the entities for the figures; here the grouping does not matter,
    # so both levels are flattened and the first name match wins.
    wanted = sys.argv[1]
    for entities in exercises.BY_LECTURE.values():
        for entity in entities:
            if entity.name == wanted:
                sys.stdout.write(stub(entity))
                return 0

    # Not every module in the course is an exercise; `ci/build.sh` decides what that means.
    print(f"no exercise entity named '{wanted}'", file=sys.stderr)
    return 1


# Run only when executed as a script, never on import, and hand the return value to the
# shell as the exit status: `ci/build.sh` tests it.
if __name__ == "__main__":
    raise SystemExit(main())
